const colors = {
  light: {
    text: "#171717",
    tint: "#1f1f1f",
    background: "#ffffff",
    foreground: "#171717",
    card: "#ffffff",
    cardForeground: "#171717",
    primary: "#1f1f1f",
    primaryForeground: "#fafafa",
    secondary: "#f7f7f7",
    secondaryForeground: "#171717",
    muted: "#f7f7f7",
    mutedForeground: "#8a8a8a",
    accent: "#f7f7f7",
    accentForeground: "#171717",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#ebebeb",
    input: "#ebebeb",
  },
  dark: {
    text: "#fafafa",
    tint: "#fafafa",
    background: "#171717",
    foreground: "#fafafa",
    card: "#1e1e1e",
    cardForeground: "#fafafa",
    primary: "#fafafa",
    primaryForeground: "#171717",
    secondary: "#2a2a2a",
    secondaryForeground: "#fafafa",
    muted: "#404040",
    mutedForeground: "#b5b5b5",
    accent: "#2a2a2a",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#404040",
    input: "#404040",
  },
  radius: 10,
};

export default colors;
