kind = "mobile"
previewPath = "/platipus-mobile/"
title = "Platipus Mobile"
version = "1.0.0"
id = "artifacts/platipus-mobile"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/platipus-mobile/" ]
localPort = 8083

[services.development]
run = "pnpm --filter @workspace/platipus-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/platipus-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/platipus-mobile", "run", "serve" ]

[services.env]
PORT = "8083"
BASE_PATH = "/platipus-mobile/"
